spring:
  application:
    name: eureka-client3
  profiles:
    active: dev,production

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
# 配置turbine
#    metadata-map:
#      cluster: MAIN