level.org.springframework.cloud: DEBUG

server:
  port: 8080

spring:
  application:
    name: gateway
  profiles:
    active: dev,production

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10

zuul:
  prefix: /api
#  ignoredServices: '*'
#  ignoredPatterns: /health,/error
#  retryable: true
  routes:
    eureka-client1: /user/**

#ribbon:
#  eureka:
#    enabled: false #配置zuul路由时用将此属性设置为false