level.org.springframework.cloud: DEBUG

server:
  port: 8080

spring:
  application:
    name: gateway
  profiles:
    active: dev,production

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10

zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    eureka-client1:
      path: /user/**
      serviceId: eureka-client1
      stripPrefix: false  # 转发时包含前缀
    test: /test/**
#  ignoredPatterns: /health,/error
#  retryable: true
  addProxyHeaders: false
  forceOriginalQueryStringEncoding: true  # 使用原始的编码

management:
  addApplicationContextHeader: false  # "X-Application-Context"

#ribbon:
#  eureka:
#    enabled: false #自定义负载均衡